const moment = require("moment");
const jQuery = require("jquery")
const angular = require("angular");
const WCPShared = require("@wcp/wcpshared");
//var WARIO_ENDPOINT = "https://wario.windycitypie.com/";
var WARIO_ENDPOINT = "http://localhost:4001/";
var EXTRAS_CATID = "5ef6cf1a3991a469ceda2598";
var PIZZAS_CATID = "5eb21d084f5f1946916c6baf";
var PIZZA_PCID = "5f074fb8a117bf46f6553aad";
var TOPPINGS_MTID = "5ef6cf743991a469ceda25aa";
var SAUCE_MTID = "5ef6cf6b3991a469ceda25a6";
var SAUCE_WHITE_OID = "5ef6d0ac3991a469ceda25d9";
var TOPPING_BLEU_OID = "5f06f2bca117bf46f6553a51";
var WCP_BLOG_LOAD_TIME = moment(new Date());//[WCP_blog_epoch_time]));
var CONFIG_ALLOW_SLICING = false;
var ENABLE_DINE_IN = false;
var ADD_SOMETHING_THRESHOLD = 2;
var CONST_MESSAGE_ADD_MORE_TO_PIZZA = "Our pizza is designed as a vehicle for add-ons. We recommend at least two toppings to weigh the crust down during baking. If this is your first time dining with us, we'd suggest ordering a menu pizza without modifications.";
var CONST_MESSAGE_REQUEST_VEGAN = "Our pizzas cannot be made vegan or without cheese. If you're looking for a vegan option, our Beets By Schrute salad can be made vegan by omitting the bleu cheese.";
var CONST_MESSAGE_REQUEST_HALF = "While half toppings are not on the menu, we can do them (with the exception of half roasted garlic or half red sauce, half white sauce) but they are charged the same as full toppings. As such, we recommend against them as they're not a good value for the customer and an imbalance of toppings will cause uneven baking of your pizza.";
var CONST_MESSAGE_REQUEST_SLICING = "In order to ensure the quality of our pizzas, we will not slice them. We'd recommend bringing anything from a bench scraper to a butter knife to slice the pizza. Slicing the whole pizza when it's hot inhibits the crust from properly setting, and can cause the crust to get soggy both during transit and as the pie is eaten. We want your pizza to be the best possible and bringing a tool with which to slice the pie will make a big difference. You will need to remove this request to continue with your order.";
var CONST_MESSAGE_TIP_PREAMBLE = "The Windy City Pie family is working hard to serve you, safely. All gratuity is shared with the entire staff. Everyone, from our team that makes the house-made dough, to the staff that handles your order appreciates your support!";
var DELIVERY_LINK = "http://bit.ly/2QsrfV8";
import "./order_angular";
import "./order.css";
import html from "./order.html";